### ISSUE TITLE
Newbie question - Can I even use Mandalorian?

### ISSUE THREAD

**Issue by jamlover** [rvolden/Mandalorion#1]
Hi. I just downloaded our very first batch of ONT cDNA reads ever from the contractor we use for sequencing, and wish to assemble transcripts using these data. I searched online to find out potential assemblers and found a master's thesis online that evaluated Mandalorian, so I went ahead and downloaded Mandalorian and got it set up. But then I see that Mandalorian as input takes reads that resulted from R2C2. From looking around online a bit it seems to me that R2C2 is not a standard process, so it's extremely likely that the "standard workflow" ONT data our contractor generated is not the result of R2C2. Assuming I am right about my data not being R2C2, does that mean there is no way for me to use Mandalorian?

Thanks in advance for answering this question, and I apologize for having to ask such a basic question.

John Martinson

**Comment by rvolden** [comment]
No problem dude, this happens more than you'd think. Mandalorion is specifically designed for long reads with high single molecule coverage (R2C2 or PacBio). The main difference between normal ONT reads and R2C2 is that R2C2 is more accurate due to higher single molecule coverage. This means that Mandalorion would not work very well for your dataset.

Luckily, if you want to do transcriptome analyses on ONT reads, there are a few good tools that you can try. I recommend [FLAIR](https://github.com/BrooksLabUCSC/flair), [stringtie2](https://github.com/gpertea/stringtie), and [pinfish](https://github.com/nanoporetech/pinfish). If you're looking for the one that's most similar to Mandalorion, I'd suggest pinfish. However, both FLAIR and stringtie2 are widely used in the long read transcriptome space. Hope this helps!

**Comment by jamlover** [comment]
Yes, it does. I actually have flair downloaded already too, so down that path I go. Thanks much for the quick response
